### ISSUE TITLE
On a Mac and Receive Installation Error

### ISSUE THREAD

**Issue by tzarger** [monostream/cert-manager-linode#4]
When I run: `helm install cert-manager-linode chart/ -n cert-manager`

I receive the error: `Error: INSTALLATION FAILED: failed to download "chart/"`

Am I missing a dependency?

Here is my repo list:

NAME         	URL                                       
ingress-nginx	https://kubernetes.github.io/ingress-nginx
jetstack     	https://charts.jetstack.io

Here is the debug info, if helpful.

```
helm install cert-manager-linode chart/ -n cert-manager --debug
install.go:178: [debug] Original chart version: ""
Error: INSTALLATION FAILED: repo chart not found
helm.go:84: [debug] repo chart not found
helm.sh/helm/v3/pkg/downloader.pickChartRepositoryConfigByName
	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:368
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).ResolveChartVersion
	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:253
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
	helm.sh/helm/v3/pkg/downloader/chart_downloader.go:90
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
	helm.sh/helm/v3/pkg/action/install.go:753
main.runInstall
	helm.sh/helm/v3/cmd/helm/install.go:190
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:125
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.3.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.3.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.3.0/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:255
runtime.goexit
	runtime/asm_arm64.s:1133
INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.3.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.3.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.3.0/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:255
runtime.goexit
	runtime/asm_arm64.s:1133
```

**Comment by tzarger** [comment]
@adrianliechti Any possible help here? Under a bit of a deadline and really need wildcard subdomains. Any help greatly appreciated. I suspect either I missing a dependency or perhaps does not work on a Mac with M1 chip as I see a reference to `asm_arm64` in the debug information.

**Comment by adrianliechti** [comment]
hello troy

I have limited possibilities since I no longer work for monostream :)


the second parameter "chart/" refers to the helm chart to install. this can be on a repository (which can be managed with helm add) or to a local folder - which is used in the readme.

try the following:
- download the whole repository (using git clone or the download-as-zip function in the github web ui)
- extract it somewhere on your disk
- open a Terminal and navigate to the root of the repo (where publish.sh) is
- try again to install

as far as I know, the actual docker image is built with x64 only.
(https://hub.docker.com/r/monostream/cert-manager-linode/tags)

this might only be an issue depending on what target system (your kubernetes cluster) you run.
if this is an non-x64 system too, the container wont start (but the helm command would succeed anyway).
the architecture of your client (e.g. macbook) should make no impact.

hope that helps
